spring:
  application:
    name: elasticsearch-study
  profiles:
    active: local
  data:
    elasticsearch:
      cluster-name: elasticsearch #cluster-name要与elasticsearch.yml中使用的集群名称一致
      cluster-nodes: localhost:9300
      repositories:
        enabled: true

server:
  port: 9779
  servlet:
    context-path: /es